# Generated by Django 4.1.4 on 2023-01-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0003_alter_reservation_age_alter_reservation_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
