# Generated by Django 4.1.4 on 2023-01-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0004_alter_reservation_phone"),
    ]

    operations = [
        migrations.DeleteModel(name="Event",),
    ]
