# Generated by Django 4.1.4 on 2023-01-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0006_regularreservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
