# Generated by Django 4.1.4 on 2023-01-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0007_reservation_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="admin_comment",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
