# Generated by Django 4.1 on 2023-01-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0009_place_alter_reservation_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="regularreservation",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="regularreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "신청가능"),
                    ("1", "신청대기"),
                    ("2", "검토중"),
                    ("3", "승인완료"),
                    ("4", "재확인 필요"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="regularreservation",
            name="date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calender.regulardate",
            ),
        ),
    ]
