# Generated by Django 4.1 on 2023-01-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0010_regulardate_regularreservation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regularreservation",
            name="status",
            field=models.CharField(
                choices=[("1", "신청대기"), ("2", "검토중"), ("3", "승인완료"), ("4", "재확인 필요")],
                max_length=1,
            ),
        ),
    ]
