# Generated by Django 4.1.4 on 2023-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0011_alter_regularreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreservation',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
