# Generated by Django 4.1 on 2023-01-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0013_alter_regularreservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularreservation",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calender.place",
            ),
        ),
    ]
