# Generated by Django 4.1 on 2023-01-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0014_regularreservation_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularreservation",
            name="admin_comment",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
